### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Murthy10** [Sebubu/BringToAfrica#8]
- [x] Project NavBar @lukasmartinelli 
- [ ] Project erfassen Anchor Tags @lukasmartinelli 
- [x] Domain Model Relation Diskussion @lukasmartinelli 
- [x] Change Play Logo to BringToAfrica @manuelroth
- [ ] Implementation Multiple DonationGoals @manuelroth
- [ ] Write Unittest for Controller Methods @Sebubu
- [x] Cleanup Template @manuelroth
- [x] Bestätigungsseite 'Projekt erstellen' entfernen @manuelroth

**Comment by manuelroth** [comment]
Weiter Sachen
- Save funktioniert noch nicht ganz (unidirektional) -> Mehrmalige Sachen müssen raus
- Status wird mitgegegben, vielleicht besser machen

**Comment by manuelroth** [comment]
Müssen wir noch im Jira nachtragen.
